### PR TITLE
fix staff profiles tables look

### PR DESCRIPTION
**Pull request by mattkeehan**

### CODE REVIEW

**Comment by joelsmithucl** [comment]
Hi Matt 

shouldn't profile table be at the silva level rather than indigo, as I assume this is for the economics site?

**Comment by mattkeehan** [comment]
I didn't want to add an Economics stylesheet just for these lines, but I can if you think it's best - sounds like they'll be having their own design soon anyway?

**Comment by joelsmithucl** [comment]
Yes definitely - 

indigo is our framework that is a separate entity to silva and should not be polluted with any silva specific style - 
palette style sheets are for silva wide overwrites and additions to core indigo 
and the site specific style sheet is for site specific overwrites and additions to core silva

**Comment by joelsmithucl** [comment]
please take the staff profile out of this pull I can then approve it. please move the profile styles to an economics style sheet.

**Pull request closed without merging**
